### ISSUE TITLE
Discuss: Add option to define allowed `sudo` commands for service user?

### ISSUE THREAD

**Issue by andreashaerter** [foundata/ansible-collection-acmesh#6]
It's very common to restart or reload services via hooks after `acme.sh` has completed its work.

Currently, we recommend this approach in the README using `community.general.sudoers`:

```yaml
- name: "Allow the acme.sh service user to reload / restart services with managed certificates"
  community.general.sudoers:
    name: "acmesh-service"
    user: "acmesh"  # Defined via the `run_acmesh_user` role variable, defaults to "acmesh"
    commands:
      - "/bin/systemctl reload apache2.service"
      - "/bin/systemctl reload nginx.service"
      - "/bin/systemctl restart postfix.service"
    nopassword: true
```

### Proposal

Should we add a role variable to allow users to specify a list of allowed `sudo` commands for the `run_acmesh_user` directly in the role?

This would simplify configuration and make it easier to manage such settings. We could also provide a sensible default list covering common web and mail servers (e.g., Apache, Nginx, Postfix).

### Benefits

- More convenient and consistent setup for users
- Reduced need to write custom `sudoers` tasks manually
- Easier onboarding for new users of the role

### Questions

- Should we include a default list of common services?
- Should the role manage the sudoers entry automatically if the list is provided?
- Any security concerns with this approach?

Feedback and suggestions welcome!
